server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/bookteria_identity
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

jwt:
  signerKey: "1TjXchw5FloESb63Kc+DFhTARvpWL4jUGCwfGWxuG5SIf/1y/LgJxHnMqaF6A/ij"

app:
  services:
    profile: http://localhost:8081/profile/
